language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^8.7

notifications:
  email:
    - dev@arndtteunissen.de

sudo: false
addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - .Build/bin/php-cs-fixer fix --dry-run --verbose --diff-format=udiff

deploy:
  provider: script
  on:
      branch: master
  script: ./ter_deploy.sh
