language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1

notifications:
  email:
    - dev@arndtteunissen.de

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini

script:
  - >
    echo;
    echo "PHP Linting";
    find . -name \*.php -exec php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "PHP CS Linting";
    composer run-script cs

deploy:
  provider: script
  on:
      branch: master
  script:
    if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
      composer require --dev namelesscoder/typo3-repository-client:^1.2.0

      git reset --hard HEAD && git clean -fx

      TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`

      echo "Uploading release ${TRAVIS_TAG} to TER"
      .Build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
    fi;
